apps/front/models.py
from ext import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    phone = db.Column(db.String(11), nullable=False)
    email = db.Column(db.String(50), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    books = db.relationship('Book', backref=db.backref('users'), lazy='dynamic')

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        return check_password_hash(self.password, raw_password)


class Book(db.Model):
    __tablename__ = 'book'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    book_name = db.Column(db.String(255), nullable=False)
    book_author = db.Column(db.String(255))
    book_category = db.Column(db.String(255))
    is_paper = db.Column(db.Boolean, default=1)
    publisher = db.Column(db.String(255))
    price = db.Column(db.Float())
    actual_price = db.Column(db.Float())
    receive_time = db.Column(db.DateTime)
    begin_read_time = db.Column(db.DateTime)
    finish_read_time = db.Column(db.DateTime)
    author_profile = db.Column(db.Text)
    book_profile = db.Column(db.Text)
    reading_notes = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

apps/front/forms.py
from wtforms import Form, StringField, PasswordField
from wtforms.validators import InputRequired, Length, Email, DataRequired, EqualTo


class LoginForm(Form):
    """
    登录验证表单
    """
    username = StringField(validators=[InputRequired(message='请输入用户名')])
    password = StringField(validators=[InputRequired(message='请输入密码'), Length(6, 24, message='密码长度不对')])
    remember = StringField()


class RegisterForm(Form):
    """
    注册验证表单
    """
    telephone = StringField('telephone', validators=[DataRequired(), Length(min=11, max=11, message='手机号码只能是11位')])
    # sms = StringField('sms_captcha', validators=[DataRequired(), Length(min=4, max=4, message='验证码不对或已过期')])
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired(), Length(min=6, max=24, message='密码长度必须在6-24位之间')])
    confirm = PasswordField('confirm', validators=[DataRequired(), EqualTo('password', message='两次输入密码必须保持一致')])
    email = StringField('email', validators=[DataRequired(), Email()])


class BookForm(Form):
    """
    添加书籍表单
    """
    book_name = StringField('book_name', validators=[DataRequired(message='请输入书名')])
    book_author = StringField('book_Author', validators=[DataRequired(message='请输入作者姓名')])

apps/front/__init__.py
from .views import bp
import apps.front.models_new
# import apps.front.hooks
# from .hooks import *

apps/front/views.py
#!usr/bin/env python  
# -*- coding:utf-8 -*-  
# @author: Johnathon Qiang
# @file  : views.py
# @time  : 2017/11/24 19:57:14
# @description：

from flask import (
    Blueprint,
    views,
    render_template,
    redirect,
    url_for,
    request,
    session,
    make_response,
    flash,
    g)
from .forms import LoginForm, RegisterForm, BookForm
# from .models import User, Book
from .models_new import User, Book
from config import DevConfig
from ext import db
import random
from utils.captcha import Captcha
from io import BytesIO

bp = Blueprint('front', __name__)


@bp.route('/captcha/')
def graph_captcha():
    # 获取验证码
    text, image = Captcha.gene_graph_captcha()
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


@bp.route('/')
def index():
    """前台主页面"""
    return render_template('front/index.html')


class SignUpView(views.MethodView):
    """前台用户注册"""

    def get(self):
        return render_template('front/signup.html')

    def post(self):
        form = RegisterForm(request.form)
        if form.validate():
            user = User()
            telephone = form.telephone.data
            username = form.username.data
            password = form.password.data
            confirm = form.confirm.data
            email = form.email.data

            if password == confirm:
                user.telephone = telephone
                user.username = username
                user.password = password
                user.email = email
                db.session.add(user)
                db.session.commit()
                return redirect(url_for('front.signin'))
            else:
                return '两次密码不一致'
        return '验证不通过'


class SignInView(views.MethodView):
    """前台用户登录"""

    def get(self):
        return render_template('front/signin.html')

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            username = form.username.data
            password = form.password.data
            remember = form.remember.data

            user = User.query.filter_by(username=username).first()
            if user and user.check_password(password):
                session[DevConfig.USER_ID] = user.id
                if remember:
                    session.permanent = True
                return redirect(url_for('front.index'))
            else:
                print('用户名或密码错误')
                return self.get()
        else:
            print('验证不通过：%s' % form.errors)
            return self.get()


bp.add_url_rule('/signup/', view_func=SignUpView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SignInView.as_view('signin'))


@bp.route('/logout/')
def logout():
    del session[DevConfig.USER_ID]
    return redirect(url_for('front.signin'))


@bp.route('/list/')
def list():
    """图书展示页面"""

    books = None
    book_random = None
    # 已登录用，查看所有属于自己的记录
    if DevConfig.USER_ID in session:
        books = Book.query.filter(Book.user_id == session[DevConfig.USER_ID]).all()
    else:
        # 未登录用户随机查看十条记录
        books_random = Book.query.all()
        print(books_random)
        if len(books_random) > 5:
            book_random = random.sample(Book.query.all(), 5)
        else:
            book_random = books_random

    return render_template('front/list_books.html', books=books, book_random=book_random)


class BookView(views.MethodView):
    """图书编辑页面视图"""

    def get(self):
        return render_template('front/add_books.html')

    def post(self):
        form = BookForm(request.form)
        if form.validate():
            book = Book()
            book_name = form.book_name.data
            book_author = form.book_author.data
            book.book_name = book_name
            book.book_author = book_author
            book.user_id = g.user.id
            db.session.add(book)
            db.session.commit()
            print('%s添加成功！' % book_name)
            return redirect(url_for('front.list'))
        else:
            print(form.errors)
            return self.get()


bp.add_url_rule('/add/', view_func=BookView.as_view('add'))


class UserInfoView(views.MethodView):
    def get(self):
        return render_template('front/user_info.html')

    def post(self):
        pass

bp.add_url_rule('/user/', view_func=UserInfoView.as_view('user'))


@bp.before_request
def my_before_request():
    # user_id = session.get(DevConfig.USER_ID)
    # if user_id:
    #     user = User.query.filter(User.id == user_id).first()
    #     if user:
    #         g.user = user
    if DevConfig.USER_ID in session:
        user_id = session.get(DevConfig.USER_ID)
        user = User.query.get(user_id)
        if user:
            g.user = user


@bp.context_processor
def my_context_processor():
    if hasattr(g, 'user'):
        return {'user': g.user}
    return {}

#
# class LoginView(views.MethodView):
#     def get(self):
#         return render_template('front/login.html')
#
#     def post(self):
#         form = LoginForm(request.form)
#
#         if form.validate():
#             username = form.username.data
#             password = form.password.data
#             remember = form.remember.data
#
#             user = User.query.filter_by(username=username).first()
#             if user and user.check_password(password):
#                 session[DevConfig.USER_ID] = user.id
#                 if remember:
#                     session.permanent = True
#                 return redirect(url_for('front.index'))
#             else:
#                 flash('用户名或密码有误', 'errors')
#                 return self.get()
#         else:
#             # message = form.errors.popitem()[1][0]
#             return self.get()

# bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))

# @bp.route('/register/', methods=['GET', 'POST'])
# def register():
#     if request.method == 'POST':
#         user = User()
#         username = request.form.get('username')
#         password = request.form.get('password')
#         email = request.form.get('email')
#         phone = request.form.get('phone')
#         user.username = username
#         user.password = password
#         user.email = email
#         user.phone = phone
#         if user.username and user.password:
#             db.session.add(user)
#             db.session.commit()
#             return redirect(url_for('front.login'))
#         else:
#             flash('用户名和密码不能为空', 'error')
#             return render_template('front/register.html')
#     return render_template('front/register.html')

templates/front/_macros.html
{% macro static(filename) %}
    {{ url_for('static', filename=filename) }}
{% endmacro %}

templates/front/base.html
{% from 'front/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-iRemember</title>
{#    <link rel="icon" type="image/png" sizes="96x96" href="https://static001.geekbang.org/static/www/img/favicon-96x96.8e64510.png">#}
    <link rel="icon" type="image/png" sizes="96x96" href="{{ static('images/document_edit.png') }}">
    <link rel="stylesheet" href="{{ static('css/bulma-0.6.0/css/bulma.css') }}">
    <link rel="stylesheet" href="{{ static('css/font-awesome-4.7.0/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ static('css/base.css') }}">
    {% block head %}{% endblock %}
</head>
<body>

<section class="hero is-light is-fullheight">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head is-primary" style="background-color: #fff">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item main-logo">
                        {# <img src="https://bulma.io/images/bulma-type-white.png" alt="Logo">#}
                        我是Logo
                    </a>
                    <span class="navbar-burger burger" data-target="navbarMenuHeroC">
            <span></span>
            <span></span>
            <span></span>
          </span>
                </div>
                <div id="navbarMenuHeroC" class="navbar-menu">
                    <div class="navbar-end">
                        <a class="navbar-item" href="{{ url_for('front.index') }}">
                            首页
                        </a>
                        <a class="navbar-item" href="{{ url_for('front.list') }}">
                            阅读
                        </a>
                        <a class="navbar-item">
                            影视
                        </a>
                        <a class="navbar-item">
                            论坛
                        </a>
                        <a class="navbar-item" href="http://xuanxiewu.com" target="_blank">
                            博客
                        </a>
                        <span class="navbar-item">
                            {% if user %}
                                <a class="button is-info is-inverted" href="{{ url_for('front.user') }}">
                                <span class="icon">
                                  <i class="fa fa-user"></i>
                                </span>
                                <span>{{ user.username }}</span>
                              </a>&nbsp;
                                <a class="button is-info is-inverted" href="{{ url_for('front.logout') }}">
                                <span class="icon">
                                  <i class="fa fa-sign-out"></i>
                                </span>
                                <span>注销</span>
                              </a>
                            {% else %}
                                <a class="button is-info is-inverted" href="{{ url_for('front.signin') }}">
                                <span class="icon">
                                  <i class="fa fa-sign-in"></i>
                                </span>
                                <span>登录</span>
                              </a>&nbsp;
                                <a class="button is-info is-inverted" href="{{ url_for('front.signup') }}">
                                <span class="icon">
                                  <i class="fa fa-info"></i>
                                </span>
                                <span>注册</span>
                              </a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </header>
    </div>
    {#    <hr>#}
    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
        <div class="container has-text-centered">
            {% block body %}{% endblock %}
        </div>
    </div>

    <!-- Hero footer: will stick at the bottom -->
    <div class="hero-foot">
        <nav class="tabs is-boxed is-fullwidth">
            <div class="container">
                <div class="clumns">
                    <div class="column is-6 is-offset-3">
                        <div class="has-text-centered">
                            <p class="footer-copyright">@copyright 2017 saltfish.cn | All rights rserved</p>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</section>


</body>
</html>

templates/front/index.html
{% extends 'front/base.html' %}
{% from 'front/_macros.html' import static %}
{% block title %}爱记{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ static('css/index.css') }}">
{% endblock %}

{% block body %}
{#    <form action="" method="post">#}
        <div class="index-title">
            <h1>iRemember</h1>
        </div>
        <div class="columns">
            <div class="column is-6 is-offset-3">
                <div class="has-text-centered">
                    <p class="control">
                        <input class="input is-large main-search" placeholder="请输入你要搜索的关键词...">
                    </p>
                    <br>
                    <button type="submit" class="button is-info is-medium lib-btn" style="border-radius: 25px">搜索图书
                    </button>
                    <button type="submit" class="button is-info is-medium mv-btn" style="border-radius: 25px">搜索电影
                    </button>
                </div>
            </div>
        </div>
{#    </form>#}

{% endblock %}

templates/front/list_books.html
{% extends 'front/base.html' %}
{% block title -%}
    图书信息
{%- endblock %}

{% block body %}

    {% if user %}
        {% if books %}
            {% for book in books %}
                <p>{{ book.book_name }}</p>
            {% endfor %}
            <p>继续<a style="color: #209cee" href="{{ url_for('front.add') }}">添加图书</a></p>
        {% else %}
            {{ user.username }}还没有添加过图书，请先 <a style="color: #00b89c" href="{{ url_for('front.add') }} ">添加图书</a>
        {% endif %}
    {% else %}
        {% if book_random %}
            {% for book in book_random %}
                <p>{{ book.book_name }}</p>
            {% endfor %}
            <a style="color: #209cee" href="{{ url_for('front.signin') }}">登录</a>查看更多图书资源
        {% else %}
            系统中还没有一本书,赶紧<a style="color: #00b89c" href="{{ url_for('front.signin') }}">登录</a>添加图书吧
        {% endif %}
    {% endif %}


{% endblock %}

templates/front/login.html
{% extends 'front/base.html' %}
{% from 'front/_macros.html' import static %}

{% block title %}
    登录
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('css/login.css') }}">
{% endblock %}

{% block body %}
    <form action="{{ url_for('front.login') }}" method="POST">
        <div class="columns">
            <div class="column is-4 is-offset-4">
                <div class="has-text-centered">
                    <div class="login-body">
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="text" name="username" placeholder="请输入用户名">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-user"></i>
                                </span>
                            </p>
                        </div>
                        <br>
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="password" name="password" placeholder="请输入密码">
                                <span class="icon is-small is-left">
                                <i class="fa fa-lock"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <label class="checkbox">
                                <input type="checkbox" name="remember" value="1">
                                记住我
                            </label>
                        </div>
                        {% if not username and not password %}
                            <p style="color: red ;margin-bottom: 10px">{{ get_flashed_messages()[0] }}</p>
                        {% else %}
                            <p style="color: red ;margin-bottom: 10px">{{ get_flashed_messages()[1] }}</p>
                        {% endif %}

                        <input class="button is-primary  is-medium" type="submit" value="登录">
                        <p class="go-register">没有账号？
                            <a style="color: #00b89c;" href="{{ url_for('front.register') }}">立即注册&nbsp;
                                <i class="fa fa-long-arrow-right"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
{#        {% for message in get_flashed_messages() %}#}
{#            <p style="color: red ;margin-bottom: 10px">{{ message }}</p>#}
{#        {% endfor %}#}
    </form>
{% endblock %}

templates/front/register.html
{% extends 'front/base.html' %}

{% block title %}
    注册
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
{% endblock %}

{% block body %}
    <form action="{{ url_for('front.register') }}" method="post">
{#    {{ form.csrf_token }}#}
        <div class="columns">
            <div class="column is-4 is-offset-4">
                <div class="has-text-centered">
                    <div class="login-body">
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="text" name="username" placeholder="请输入用户名">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-user"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="password" name="password" placeholder="请输入密码">
                                <span class="icon is-small is-left">
                                <i class="fa fa-lock"></i>
                                </span>
                            </p>
                        </div>

                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="password" name="confirm" placeholder="请确认密码">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-lock"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control has-icons-left has-icons-right">
                                <input class="input is-primary" type="email" name="email" placeholder="请输入邮箱地址">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-envelope"></i>
                                </span>
                                <span class="icon is-small is-right">
                                    <i class="fa fa-check"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="tel" name="phone" placeholder="请输入手机号码">
                                <span class="icon is-small is-left">
                                <i class="fa fa-phone"></i>
                                </span>
                            </p>
                        </div>
                        <br>
                        {% for message in get_flashed_messages() %}
                            <p style="color: red ;margin-bottom: 10px">{{ message }}</p>
                        {% endfor %}
                        <input class="button is-primary is-medium btn-block" type="submit" value="立即注册">
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/front/signin.html
{% from 'front/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录-iRemember</title>
    <link rel="icon" type="image/png" sizes="96x96" href="{{ static('images/document_edit.png') }}">
    <link rel="stylesheet" href="{{ static('css/bulma-0.6.0/css/bulma.css') }}">
    <link rel="stylesheet" href="{{ static('css/font-awesome-4.7.0/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ static('css/signup_signin.css') }}">
    <style>
        img {
            cursor: pointer;
        }

        #captcha-img {
            cursor: pointer;
        }
    </style>
</head>
<body>
<div class="main-box">
    <div class="logo-box">
        <a href="/">
            <img src="{{ static('images/me.jpeg') }}" alt="">
        </a>
    </div>
    <h2 class="page-title">iRemember-登录</h2>
    <hr>
    <form action="{{ url_for('front.signin') }}" method="post">
        <div class="form-box">
            <div class="field">
                <div class="control has-icons-left">
                    <input class="input" type="text" placeholder="用户名/手机号/邮箱" name="username">
                    <span class="icon is-small is-left">
                    <i class="fa fa-user"></i>
                </span>
                </div>
            </div>
            <div class="field">
                <div class="control has-icons-left">
                    <input class="input" type="password" placeholder="密码" name="password">
                    <span class="icon is-small is-left">
                    <i class="fa fa-lock"></i>
                    </span>
                </div>
            </div>
            <div class="field has-addons">
                <p class="control">
                    <input class="input" type="text" placeholder="图形验证码" name="graph_captcha">
                </p>
                <p class="control graph-captcha">
                    <a class="button is-static captcha-addon">
                        <img id="captcha-img" src="{{ url_for('front.graph_captcha') }}" alt="">
                    </a>
                </p>
            </div>
            <div class="field">
                <div class="control">
                    <div class="checkbox ">
                        <label class="auto-login">
                            <input type="checkbox" value="1" name="remember">&nbsp;&nbsp;10天内免登陆
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <a href="" class="forgot_pwd"><span>忘记密码？</span></a>
                        </label>
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <button class="button is-info login-btn">立即登录</button>
                </div>
            </div>
            <div class="field">
                <div class="control registered">
                <span>没有账号？ <a href="{{ url_for('front.signup') }}">立即注册 &nbsp;<i
                        class="fa fa-long-arrow-right"></i></a></span>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="hero-foot">
    <nav class="tabs is-boxed is-fullwidth">
        <div class="container">
            <div class="clumns">
                <div class="column is-6 is-offset-3">
                    <div class="has-text-centered">
                        <p class="footer-copyright">@copyright 2017 saltfish.cn | All rights rserved</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
</body>
</html>

templates/front/signup.html
{#{% extends 'front/base.html' %}#}
{% from 'front/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册-iRemember</title>
    <link rel="icon" type="image/png" sizes="96x96" href="{{ static('images/document_edit.png') }}">
    <link rel="stylesheet" href="{{ static('css/bulma-0.6.0/css/bulma.css') }}">
    <link rel="stylesheet" href="{{ static('css/font-awesome-4.7.0/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ static('css/signup_signin.css') }}">
</head>
<body>
<div class="main-box">
    <div class="logo-box">
        <a href="/">
            <img src="{{ static('images/me.jpeg') }}" alt="">
        </a>
    </div>
    <h2 class="page-title">iRemember-注册</h2>
    <hr>
    <form action="{{ url_for('front.signup') }} " method="post">
        <div class="form-box">
            <div class="field has-addons">
                <div class="control has-icons-left">
                    <input class="input" type="text" placeholder="手机号码" name="telephone">
                    <span class="icon is-small is-left">
                    <i class="fa fa-phone"></i>
                </span>
                </div>
                <div class="control">
                    <a class="button is-info">
                        发送验证码
                    </a>
                </div>
            </div>
            <div class="field">
                <div class="control has-icons-left">
                    <input class="input" type="text" placeholder="短信验证码" name="sms_captcha">
                    <span class="icon is-small is-left">
                    <i class="fa fa-phone"></i>
                </span>
                </div>
            </div>
            <div class="field">
                <div class="control has-icons-left">
                    <input class="input" type="text" placeholder="邮箱" name="email">
                    <span class="icon is-small is-left">
                    <i class="fa fa-envelope"></i>
                </span>
                </div>
            </div>
            <div class="field">
                <div class="control has-icons-left">
                    <input class="input" type="text" placeholder="用户名" name="username">
                    <span class="icon is-small is-left">
                    <i class="fa fa-user"></i>
                </span>
                </div>
            </div>
            <div class="field">
                <div class="control has-icons-left">
                    <input class="input" type="password" placeholder="密码" name="password">
                    <span class="icon is-small is-left">
                    <i class="fa fa-lock"></i>
                </span>
                </div>
            </div>
            <div class="field">
                <div class="control has-icons-left">
                    <input class="input" type="password" placeholder="确认密码" name="confirm">
                    <span class="icon is-small is-left">
                    <i class="fa fa-lock"></i>
                </span>
                </div>
            </div>
            <div class="field has-addons">
                <p class="control ">
                    <input class="input" type="text" placeholder="图形验证码" name="graph_captcha">
                </p>
                <p class="control graph-captcha">
                    <a class="button is-static captcha-addon">
                        <img src="{{ url_for('front.graph_captcha') }}" alt="">
                    </a>
                </p>
            </div>
            <div class="field">
                <div class="control">
                    <button class="button is-info reg-btn" type="submit">立即注册</button>
                </div>
            </div>
            <div class="field">
                <div class="control registered">
                    <span>已经有账号？点此 <a href="{{ url_for('front.signin') }}">登录</a></span>
                </div>
            </div>

        </div>
    </form>
</div>
<div class="hero-foot">
    <nav class="tabs is-boxed is-fullwidth">
        <div class="container">
            <div class="clumns">
                <div class="column is-6 is-offset-3">
                    <div class="has-text-centered">
                        <p class="footer-copyright">@copyright 2017 saltfish.cn | All rights rserved</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
</body>
</html>

templates/front/user_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户详情-iRemember</title>
</head>
<body>
<h2>用户名：{{ user.username }}</h2>
<h2>手机号码：{{ user.telephone }}</h2>
<h2>email：{{ user.email }}</h2>
<h2>注册时间：{{ user.create_time }}</h2>
</body>
</html>